---
title: "Seeds"
output: html_document
date: '2022-03-09'
---

```{r}
library(coda)
library(gtools)
```


# Data

```{r}
"I" <- 
21
"r" <-
c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46, 10, 8, 10, 8, 23, 0, 
3, 22, 15, 32, 3)
"n" <-
c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79, 13, 16, 30, 28, 45, 
4, 12, 41, 30, 51, 7)
"x1" <-
c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1)
"x2" <-
c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 
1)
```

# Initialisation 

```{r}
alpha0 <- 0
alpha1 <- 0
alpha2 <- 0
alpha12 <- 0
tau <- 10
b <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0)
```



```{r}
gibbsSeeds <- function(nchain, prop_sd){
  
  #Calcul de p_i
  p <- inv.logit(alpha0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b)
  
  chain <- matrix(NA, nchain+1, 5+I)
  chain[1,] <- c(alpha0, alpha1, alpha2, alpha12, tau, b)
  
  #prop_b <- rep(NA, I)
  prop_b <- 0
  
  for (i in 1:nchain){
    
    #Mise à jour de alpha0
    prop_a0 <- rnorm(1, alpha0, prop_sd[1])
    prop_p <- inv.logit(prop_a0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b)
    
    prop_linear <- prop_a0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    prop_p <- exp(prop_linear) / (1 + exp(prop_linear))
    
    top <- -0.5 * prop_a0^2 / 10^6 + sum(r * prop_linear) + sum(n * log1p(-prop_p))
    
    linear <- alpha0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    p <- exp(linear) / (1 + exp(linear))
    
    bottom <- -0.5 * alpha0^2 / 10^6 + sum(r * linear) + sum(n * log1p(-p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha0 <- prop_a0
      p <- prop_p
    }
    
    #Mise à jour de alpha1
    prop_a1 <- rnorm(1, alpha1, prop_sd[1])
    prop_linear <- alpha0 + prop_a1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    prop_p <- exp(prop_linear) / (1 + exp(prop_linear))
    
    top <- -0.5 * prop_a1^2 / 10^6 + sum(r * prop_linear) + sum(n * log1p(-prop_p))
    
    linear <- alpha0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    p <- exp(linear) / (1 + exp(linear))
    
    bottom <- -0.5 * alpha1^2 / 10^6 + sum(r * linear) + sum(n * log1p(-p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha1 <- prop_a1
      p <- prop_p
    }
    
    #Mise à jour de alpha2
    prop_a2 <- rnorm(1, alpha2, prop_sd[1])
    
    prop_linear <- alpha0 + alpha1*x1 + prop_a2*x2 + alpha12*x1*x2 + b
    prop_p <- exp(prop_linear) / (1 + exp(prop_linear))
    
    top <- -0.5 * prop_a2^2 / 10^6 + sum(r * prop_linear) + sum(n * log1p(-prop_p))
    
    linear <- alpha0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    p <- exp(linear) / (1 + exp(linear))
    
    bottom <- -0.5 * alpha2^2 / 10^6 + sum(r * linear) + sum(n * log1p(-p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha2 <- prop_a2
      p <- prop_p
    }
    
    #Mise à jour de alpha12
    prop_a12 <- rnorm(1, alpha12, prop_sd[1])
    
    prop_linear <- alpha0 + alpha1*x1 + alpha2*x2 + prop_a12*x1*x2 + b
    prop_p <- exp(prop_linear) / (1 + exp(prop_linear))
    
    top <- -0.5 * prop_a12^2 / 10^6 + sum(r * prop_linear) + sum(n * log1p(-prop_p))
    
    linear <- alpha0 + alpha1*x1 + alpha2*x2 + alpha12*x1*x2 + b
    p <- exp(linear) / (1 + exp(linear))
    
    bottom <- -0.5 * alpha12^2 / 10^6 + sum(r * linear) + sum(n * log1p(-p))

    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha12 <- prop_a12
      p <- prop_p
    }
    
    #Mise à jour de tau
    
    tau <- rgamma(n=1, shape=0.001 + I/2, rate = 0.001 + sum(b**2)/2)
    
    #Mise à jour des b_i
    
    for(j in 1:I){
      prop_b <- rnorm(1, b[j], prop_sd[2])
      prop_p <- inv.logit(alpha0 + alpha1*x1[j] + alpha2*x2[j] + alpha12*x1[j]*x2[j] + prop_b)
      top <- (-tau/2)*(prop_b**2) + r[j]*log(prop_p) + (n[j]-r[j])*log(1-prop_p)
      bottom <- (-tau/2)*(b[j]**2) + r[j]*log(p[j]) + (n[j]-r[j])*log(1-p[j])
      acc_prob <- exp(top - bottom)

      if(runif(1) < acc_prob){
        b[j] <- prop_b
        p[j] <- prop_p
      }
    }
    
    #Mise à jour de ma chaîne
    chain[i+1,] <- c(alpha0, alpha1, alpha2, alpha12, tau, b)
    
  }
  colnames(chain) <- c("alpha0","alpha1", "alpha2", "alpha12", "tau", "b1","b2",
                       "b3","b4","b5","b6","b7","b8","b9","b10","b11","b12","b13","b14",
                       "b15","b16","b17","b18","b19","b20","b21")
  return(chain)
}
```

```{r}
chain <- gibbsSeeds(10000, prop_sd = c(1.5,1))

plot(mcmc(chain))

```

Estimation finale des paramètres :

```{r}
mean(chain[,"alpha0"])
mean(chain[,"alpha1"])
mean(chain[,"alpha2"])
mean(chain[,"alpha12"])
mean(chain[,"tau"])
```


